default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: postgres
  password: postgres123
  host: localhost

development:
  <<: *default
  database: lelocal_development

test:
  <<: *default
  database: lelocal_test

production:
  <<: *default
  database: lelocal_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

