default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>



