default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres123
  host: 127.0.0.1

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>




